config/routes.rb
Rails.application.routes.draw do

  get 'password_reseteos/new'

  get 'password_reseteos/edit'

  resources :password_reseteos, only: [:new, :create, :edit, :update]
  resources :envioempresas, only: [:create, :destroy]

  get 'ingresa' => 'empresessions#new'
  post 'ingresa' => 'empresessions#create'
  delete 'salir' => 'empresessions#destroy'

  get 'altaempresa' => 'empresas#nueva'

  resources :empresas

  get 'password_resets/new'

  get 'password_resets/edit'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'usuarios/new'

  root 'estaticas#home'

  get 'unete' => 'estaticas#unete'

  get 'acercade' => 'estaticas#acercade'

  get 'faq' => 'estaticas#faq'

  get 'politicas' => 'estaticas#politicas'

  get 'contacto' => 'estaticas#contacto'

  get 'privacidad' => 'estaticas#privacidad'

  get 'nuevacuenta' => 'usuarios#nueva'

  resources :usuarios
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  
  match '/cotizacion', to: 'pides#new', via: 'get'
  match '/cotizacion', to: 'pides#create', via: 'post'
  resources "cotizacion", only: [:new, :create]

end

app/controllers/estaticas_controller.rb
class EstaticasController < ApplicationController

  def home

    if logged_in?
      @micropost  = current_usuario.microposts.build
      @feed_items = current_usuario.feed.paginate(page: params[:page])
    else ingresado?
      @envioempresa = current_empresa.envioempresas.build if ingresado?
    end

  end

  def cotiza
  end

  def acercade
  end

  def faq
  end

  def unete
  end

  def politicas
  end

  def contacto
  end

  def privacidad
  end

  def rutas
  end

end

app/helpers/estaticas_helper.rb
module EstaticasHelper
end

app/views/estaticas/acercade.html.erb
<% provide(:title, "Acerca de | ") %>

<meta name="description" content="¿Nuestra visión, objetivos y valores.">

<div class="container">

	<div class="col-lg-6 col-lg-push-3 text-center">

		<header>
			<h2>Acerca de Bicimensajeros México</h2>
			<p>Logística Urbana Sustentable</p>
		</header>

	</div>
			<div class="row">
				<div class="col-lg-8 col-lg-push-2">
							<!-- Text -->
					<div class="">
						
						<p>Somos una empresa de profesionales en la bicimensajería que ofrece sus servicios desde el 2009 como BICIMENSAJEROS DF en el valle de México y Área Metropolitana y que inicia la expansión de nuestro concepto al interior de la República como Bicimensajero.com ,
						Nuestra organización busca desarrollar una cultura ciclista laboral  como un oficio y/ó estilo de vida, donde quienes comparten el gusto por la “bicicleta” la conceptualizan como su medio de transporte más eficaz, ecológico y que aporta salud física y mental a su persona sin importar la edad o sexo.
						</p>

						<b>Misión</b>
						
						<li>Ofrecer un servicio de mensajería y gestión, rápido, ecológico, eficiente, seguro y personalizado a nuestros clientes; que promueva el compromiso social, el desarrollo del individuo y el deporte.
						</li>
						<li>Investigación social sobre la movilidad alternativa para el desarrollo de estrategias en beneficio del medio ambiente, salud y economía.
						</li>

						<b>Visión</b>

						<li>Ser la empresa líder en México con reconocimiento y contacto internacional; a partir de la diversificación de nuestro servicio a la opción de 80% bicicleta y 20% multimodal, que brinda un servicio competitivo para la satisfacción de nuestros clientes.
						</li>

						<li>Constituirse como empresa formadora de #bicimensajeros (Casa BICIMENSAJEROS) que expanda un horizonte franqueable.
						</li>

						<b>Valores:</b>
						<li>Disciplina, Solidaridad, Correspondencia, Honestidad, Confiabilidad, Puntualidad, Responsabilidad, Prudencia y Compromiso</li>

						<ul>
							<li>
								<b>¿Por qué usar a BICIMENSAJEROS MÉXICO como ventaja de servicio?</b>
								<p>Porque ofrecemos a nuestros clientes la posibilidad de ahorrar tiempo en traslados, costo de pasajes o gasolina, renta o compra de automóvil o motocicleta, costos de nómina y carga social, carga administrativa de personal, tiempo de reclutamiento y selección de personal, capacitación y adiestramiento, uniforme, celular, bolso, etc.</p>
							</li>
							<li>
								<b>En BICIMENSAJEROS MÉXICO buscamos establecer una relación de confianza y compromiso con nuestros clientes que se firma bajo las normas del contrato de prestación de servicios profesionales.</b>
							</li>
						</ul>

					</div>

				</div>
			</div>
</div>

app/views/estaticas/contacto.html.erb
<% provide(:title, "Contacto | ") %>

<meta name="description" content="Trabaja con nosotros, paquetes para empresas y sugerencias.">
<meta name="keywords" content="Trabaja,trabajo,mensajero,urbano,logística">

<div class="container">

	<div class="row">

		<div class="col-lg-6 col-lg-push-3 text-center">

			<header>
				<h2>Ponte en contacto</h2>
				<p>Tus datos están seguros con nosotros</p>
			</header>

		</div>

	</div>

	<div class="row">
		<div class="col-lg-8 col-lg-push-2">
					<!-- Text -->
			<div class="">
				
				<p>
				  ¿Te interesa chambear con nosotros? mandale un mail al capi <%= mail_to "abraham@bicimensajero.com" %>
				</p>

				<p>
					¿Eres una empresa y necesitas un alto volumen de servicios? Te tenemos un plan a la medida, por favor contactanos con un mail a <%= mail_to "daniel@bicimensajero.com" %> 
				</p>

				<p>
					¿Nos quieres mentar la madre, darnos un arrimón (virtual), o sólo cotorrear? este mail es el adecuado: <%= mail_to "amo@bicimensajero.com" %> 
				</p>

				<p>O sencillamente quieres hablar con el mero mero, mandale un mail a <%= mail_to "ollin@bicimensajero.com" %>
				</p>

			</div>

		</div>
	</div>
</div>

app/views/estaticas/faq.html.erb
<% provide(:title, "FAQ | ") %>

<meta name="description" content="¿Cómo le hacemos? ¿Qué solidez de demanda tienen? ¿Cubren toda la ciudad o solo ciertas zonas?">
<meta name="keywords" content="Mensajería,Bicimensajeros,sustentable,urbana,urbano,bicicleta,on-demand">

<div class="container">

		<div class="col-lg-6 col-lg-push-3 text-center">
			<h2>Preguntas frecuentes.</h2>
			<p>Soluciones para ti.</p>
		</div>
		
			<div class="row">
				<div class="col-lg-8 col-lg-push-2">
							<!-- Text -->
					<ul>
							<li>
								<b>¿En verdad lo hacen en bicicleta?</b>
								SÍ, BICIMENSAJERO, somos un equipo de trabajo apasionado por el uso de la bicicleta, nuestros miembros son atletas de alto rendimiento que además de realizar el servicio por la compensación económica lo realizan de igual forma como un entrenamiento para superar sus marcas personales y templar su voluntad, los fines de semana de igual manera aplican su entrenamiento diario para realizar recorridos interestatales y/o competencias. (Te invitamos a nuestros recorridos de fin de semana si tienes la voluntad de vencer tus limitaciones y hacer chica tu Ciudad)
							</li>

							<li>
								<b>¿Cubren toda la ciudad o solo ciertas zonas?</b>
								BICIMENSAJERO cubre toda la ciudad y por largo o complicado que parezca cumplimos con el objetivo, existen ciertas zonas en la ciudad marcadas por seguridad pública como zonas roja, en estos casos notificamos al cliente por otra posible solución de entrega.
							</li>
							<li>
								<b>¿Cuántos kilómetros recorren diariamente?</b>
								En BICIMENSAJERO, por kilometraje individual oscila un promedio de 60 a 85 km por día, nuestro record interno por un día de trabajo es de 155km.
							</li>
							<li>
								<b>¿Qué solidez de demanda tienen?</b>
								En BICIMENSAJERO somos un equipo laboral que desde el 2009 ofrece sus servicios y que crece con la demanda y expansión de nuestros clientes, actualmente cubrimos las necesidades logísticas de nuestros clientes sin dificultad.
							</li>
							<li>
								<b>¿Qué es lo que comúnmente se transporta y hasta que pueden llevar?</b>
								En BICIMENSAJERO somos muy versátiles y flexibles a tu necesidad, en la mayor parte nos dedicamos a la parte logística administrativa, llevando tus facturas, cheques y proyectos; también llevamos la paquetería y esas cosas que a veces se suelen olvidar y a nosotros nos puedes encomendar para ayudarte a solucionar un problema. En sistemas de paquetes nuestras mochilas son un sistema pensado para transportar altos volúmenes que no excedan los 20 kilos y que no exceda el volumen de aproximadamente una caja de huevo. (de ser mayor pedimos nos notifiquen anticipadamente para buscar la logística adecuada.)
							</li>
							<li>
								<b>¿Facturan los servicios?</b>
								Por supuesto, somos una empresa sólida que avanza con la ley de nuestra Ciudad.
							</li>
							<li>
								<b>¿Por qué usar a BICIMENSAJERO como ventaja de servicio?</b>
								Le ofrecemos a nuestros clientes la posibilidad de ahorrar tiempo en traslados, costo de pasajes o gasolina, renta o compra de automóvil o motocicleta, costos de nómina y carga social, carga administrativa de personal, tiempo de reclutamiento y selección de personal, capacitación y adiestramiento, uniforme, celular, bolso, etc, y sobre todo; porque somos una empresa socialmente responsable con el medio ambiente y no contaminamos la Ciudad. 
							</li>
					</ul>

				</div>

			</div>
</div>

app/views/estaticas/home.html.erb
<% content_for :for_head do %>
  <meta name="google-site-verification" content="JXnpOvr29gTNULR82l5pRrE1inBClz6e7Ny0KUx9YaU" />
<% end %>

<% content_for(:body_attributes) do %>
    data-no-turbolink="true"
  <% end %>

<meta property="og:site_name" content="Bicimensajero"/>
<meta property="og:url" content="http://www.bicimensajero.com" />
<meta property="og:description" content="Servicio de logística urbana on-demand: Implementando principios de economía colaborativa. Checa cuanto CO2 le estás ahorrando al planeta." />
<meta property="og:image" content="http://www.bicimensajero.com/images/logo.png" />

<meta name="description" content="Servicio de logística urbana on-demand: Implementando principios de economía colaborativa.">
<meta name="keywords" content="Mensajería,sostenible,logística,Bicimensajero,Bicimensajeros,sustentable,urbana,urbano,bicicleta,on-demand,economía,colaborativa">

    <% if logged_in? %>

    	<div class="row">
    	   <%= render 'shared/micropost_form' %>
    	</div>

    <% elsif ingresado? %>

        <div class="row">
            <div class="col-lg-12">
                <div class="col-lg-10">
                    <%= render 'shared/envioempresa_form' %>
                </div>
                <div class="col-lg-2">
                    <%= render 'shared/empresa_info' %>
                </div>
            </div>
        </div>

	<% else %>


<!-- Banner -->
        <div class="main-container">
            <section class="fullscreen cover parallax image-bg overlay">

                <div class="background-image-holder">
                	<%= image_tag 'banner1.jpg', alt: 'bicimensajero', :class => 'background-image' %>
                </div>

                <div class="container v-align-transform">
                    <div class="row">
                        <div class="col-sm-12 text-center">
                            <h1 class="mb16">Envía y recibe tu pedido 
                                <br class="hidden-sm" /> en un solo día</h1>
                            <h6 class="uppercase mb32">Sólo con bicimensajero.com</h6>
                        </div>
                       <!--
                        <div class="col-sm-8 col-md-6 mb24">    
                            <img alt="Pic" src="img/vent1.png" />
                        </div>
                       -->
                        <div class="col-sm-12 text-center">                            
                            <%= link_to "Cotiza tu envío gratis", cotizacion_path, :class => 'btn btn-lg btn-filled' %>
                        </div>
                        <div class="col-sm-12">
                            <div class="modal-video-container pull-left">
                                <div class="play-button inline"></div>
                                <div class="modal-video">
                                    <i class="ti-close close-iframe"></i>
                                    <iframe data-src="https://www.youtube.com/embed/tTg5DE77C88" data-autoplay="1"></iframe>
                                </div>
                            </div>
                            <!--end of modal video-->
                           >
                            
                        </div>
                         
                    </div>
                    <!--end of row-->
                </div>
                <!--end of container-->
            </section>
            

            <section>
                <div class="container">
                    <div class="row">
                        <div class="col-md-8 col-md-offset-2 col-sm-12 text-center">
                            <h4 class="uppercase mb80">Así funciona nuestro servicio</h4>
                            <div class="tabbed-content icon-tabs">
                                <ul class="tabs">
                                    <li class="active">
                                        <div class="tab-title">
                                            <i class="ti-mobile icon"></i>
                                            <span>Solicita un bicimensajero</span>
                                        </div>
                                        <div class="tab-content">
                                            <p>
                                                Utiliza nuestra herramienta para <%= link_to "cotizar", cotizacion_path, :target => '_blank' %>. Crea tu cuenta y en cuanto lo solicites, tu Bicimensajero estará en camino.
                                            </p>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="tab-title">
                                            <i class="ti-package icon"></i>
                                            <span>Recojemos tu pedido</span>
                                        </div>
                                        <div class="tab-content">
                                            <p>
                                                Pasamos por tu pedido a donde nos indiques y en caso de solicitar pago en efectivo, se recolectará el dinero en el encuentro.
                                            </p>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="tab-title">
                                            <i class="ti-location-pin icon"></i>
                                            <span>Entregamos tu pedido </span>
                                        </div>
                                        <div class="tab-content">
                                            <p>
                                                Llegamos con el destinatario, entregamos tu paquete, se envia un mail de confirmación y es así como utilizaste nuestro servicio.
                                            </p>
                                        </div>
                                    </li>
                                    
                                </ul>
                            </div>
                            <!--end of icon tabs-->
                        </div>
                    </div>
                    <!--end of row-->
                </div>
                <!--end of container-->
            </section>

                <section class="bg-secondary">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-10 col-md-offset-1 col-sm-12 text-center">
                                <h3>Conoce un poco más acerca de nosotros</h3>                    
                            </div>
                        </div>
                        <!--end of row-->
                    </div>
                <!--end of container-->
                </section>
            
                <section class="p0">
                    <div>
                        <div class="col-sm-12 text-center">  
                        </div>
                    </div>
                    <div class="row masonry masonryFlyIn">
                        <div class="col-md-3 col-sm-6 masonry-item project" >
                            <div class="image-tile inner-title text-center">

                            	<%= link_to unete_path do %>                                    
                                    <%= image_tag 'unete.jpg', alt: 'Trabaja con nosotros' %>
                                    <div class="title">
                                        <h5 class="uppercase mb0">Únete a nosotros</h5>
                                        <span>Se un bicimensajero</span>
                                    </div>
                                <% end %>

                            </div>
                        </div>
                        <div class="col-md-3 col-sm-6 masonry-item project" >
                            <div class="image-tile inner-title  text-center">
                              
                                <%= link_to politicas_path do %>                                    
                                    <%= image_tag 'politicas.jpg', alt: 'Trabaja con nosotros' %>
                                    <div class="title">
                                        <h5 class="uppercase mb0">Políticas de envío</h5>
                                        <span>Mejorando cada día</span>
                                    </div>
                                <% end %>

                            </div>
                        </div>
                        <div class="col-md-3 col-sm-6 masonry-item project" >
                            <div class="image-tile inner-title  text-center">                                

                                <%= link_to faq_path do %>                                    
                                    <%= image_tag 'preguntas.jpg', alt: 'Trabaja con nosotros', width: '100%' %>
                                    <div class="title">
                                        <h5 class="uppercase mb0">Preguntas frecuentes</h5>
                                        <span>Dudas y sugerencias</span>
                                    </div>
                                <% end %>

                            </div>
                        </div>
                        <div class="col-md-3 col-sm-6 masonry-item project">
                            <div class="image-tile inner-title  text-center">                            	

                                <%= link_to acercade_path do %>                                    
                                    <%= image_tag 'cultura.jpg', alt: 'Trabaja con nosotros' %>
                                    <div class="title">
                                        <h5 class="uppercase mb0">Acerca de nosotros</h5>
                                        <span>Nuestra cultura</span>
                                    </div>
                                <% end %>

                            </div>
                        </div>
                    </div>
                <!--end of row-->
                </section>

            </div>

			<% end %>

app/views/estaticas/politicas.html.erb
<% provide(:title, "Políticas | ") %>

<meta name="description" content="Conoce nuestras políticas de envío.">

	<section class="container">

		<div class="row">

			<div class="col-lg-6 col-lg-push-3 text-center">
				<header>
					<h2>Políticas de envío</h2>
					<p></p>
				</header>
			</div>

		</div>

		<div class="row">

			<div class="col-lg-8 col-lg-push-2">

					<!-- Text -->
				<section class="box">

							<p>
							1.- El cliente debe Indicar en forma clara los datos completos de recolección y entrega así como nombres de remitente y destinatario y el detalle de alguna característica del lugar como entre calles. El error de información y/o falta de la misma que no permita concretar el envío será devuelto una vez se liquide el servicio y el regreso del documento.</p>
							<p>

							2.   	Es necesario declarar en forma escrita y veraz lo que se envía, en volumen y peso.
							<p>3.   	Si el Bicimensajero detecta falsedad en la declaración del envío, rechazará la transportación, de notar algo ilícito tiene el derecho a pedir se muestre el contenido y la obligación civil de notificar a las autoridades correspondientes.
							</p>
							<p>	
							4.   	El Bicimensajero sólo realizará actividades de acuerdo a su capacitación: recolectar y entregar en destino. Queda completamente prohibido realizar actividades fuera de la recolección, trasportación y entrega.
							</p>
							<p>
							5.   	De ser solictada una gestión, se solicita el ABC de los paso a seguir para su desarrollo y las líneas abiertas de comunicación para la correcta culminación de la misma.
							</p>
							<p>
							6.   	Bicimensajero México basa su filosofía en la confianza y la amistad sin embargo no tenemos ninguna tolerancia para el lenguaje abusivo y/o comportamiento abusivo hacia nuestra empresa y al servicio que prestamos o nuestros Bicimensajeros. Cualquier cliente que se considere a nuestra discreción abusivo hacia nuestra empresa, Bicimensajero o al servicio que prestamos, resultará en inmediata e irrevocable terminación de la cuenta sin reembolso alguno. Las amenazas de demanda, la calumnia y la difamación de cualquier índole incluyendo redes sociales, etc… son considerados formas de abuso y dará lugar a la terminación irrevocable de la relación comercial sin reembolso alguno.
																</p>

							<header>
								<h3>Nuestro compromiso.</h3>
								<p>BICIMENSAJERO Tiene el compromiso de:</p>
							</header>



							<ul>

							<li>Cumplir con los horarios pactados de 90 minutos en la recolección y entrega dentro de las zonas de cobertura de los Bicimensajeros en el DF y de 150 minutos en el Edo. de México, una vez confirmados los datos de recepción de la información.</li>

							<li>Notificar del monto del cobro antes de cada servicio para su autorización.</li>

							<li>Identificarse oficialmente como Bicimensajero y mantener una imagen pulcra, sana y deportiva siendo nosotros la imagen logística misma de tu empresa.</li>

							<li>Brindar un trato amable y cortes basando en nuestra filosofía de confianza, respeto y amistad.</li>

							<li>Ofrecer el acuse aval digital o físico de la culminación del servicio.</li>

							<li>Brindar un seguimiento empresarial a tus necesidades por medio de los ejecutivos de cuenta en atención humana a nuestros clientes.</li>
							</ul>

							<header>
							<h3>Políticas de transporte:</h3>
								
							</header>


							<ul>
								<li>
							En BICIMENSAJERO realizamos nuestros servicios de una forma rápida, en conciencia con tu producto y el medio ambiente; lo importante es tu entrega por lo que nos reservamos el derecho a elegir la vía y medio de transporte que más convenga para la culminación del mismo.</li>
							<li>
							No nos responsabilizamos en tiempos de entrega por factores ajenos a nuestra logística, como desastre natural o climatológico así como la retención del producto por alguna situación empresarial o judicial.</li>
							</ul>


							<header>
								<h3>Restricciones del servicio.</h3>
								<p>QUEDA COMPLETAMENTE PROHIBIDO:</p>
							</header>

							<ul>
								<li>Enviar y transportara alcohol y sustancias prohibidas.</li>
								<li>Fármacos y medicamentos controlados, incluidas plantas y hierbas.
							Tejidos y órganos del cuerpo, así como células madre y embriones.</li>
								<li>
							Partes de animales, fluidos o sangre.</li>
								<li>
							Armas blancas como cuchillos o navajas, armas de fuego y explosivos como detonantes y  municiones.</li>
								<li>
							Material pornográfico de menores o contenidos que se puedan percibir como erotismo y pedofilia.</li>
								<li>
							Mercancía de introducción ilícita al país y que viole las leyes aduanales que lo rigen.</li>
								<li>
							Copias de libros, películas, canciones y mercancías no autorizadas y que violen los derechos de autor, consideradas piratería.</li>
								<li>
							Lentes, trasmisores, antenas y materiales que intercepten señales considerados de espionaje en la violación de los derechos de la privacidad individual o atenten a la nación.</li>
								</ul>

					</section>

				</section>

					</div>

<!--inicia testing -->

app/views/estaticas/privacidad.html.erb
<% provide(:title, "Privacidad | ") %>

<meta name="description" content="Conoce nuestras políticas de privacidad.">

<section class="container">

	<div class="row">

		<div class="col-lg-6 col-lg-push-3 text-center">

			<header>
				<h2>Aviso de privacidad</h2>
				<p>Tus datos están seguros con nosotros</p>
			</header>

		</div>

	</div>

	<div class="row">

		<div class="col-lg-8 col-lg-push-2">
					<!-- Text -->
			<div class="">
				
				<p>La empresa <strong>BICIMENSAJERO</strong>, utilizará sus datos personales recabados con los siguientes fines:  Marketing, fiscales, para realizar cobros, para la emisión de facturas, para la realización de envíos.  Para mayor información sobre el tratamiento de sus datos personales usted puede solicitar copia de contrato a 
					<%= mail_to "ollin@bicimensajero.com", "ollin@bicimensajero.com", bcc: "amo@bicimensajero.com" %>
				  
				</p>

			</div>

		</div>

	</div>

</section>

app/views/estaticas/rutas.html.erb
    <% provide(:title, "Cotización | ") %>

    <script type="text/javascript" src="https://maps.google.com/maps/api/js?sensor=false"></script>
    
    <script>

      var rendererOptions = {
        draggable: true
      };
      var directionsDisplay = new google.maps.DirectionsRenderer(rendererOptions);;
      var directionsService = new google.maps.DirectionsService();
      var map;

      function initialize() {

        var mapOptions = {
          zoom: 14,
          scrollwheel: false,
          streetViewControl: false,
          componentRestrictions: {country: "mx"},
          mapTypeControl: false
          
        };
        map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

        // Try HTML5 geolocation
        if(navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            var pos = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
          map.setCenter(pos);
          }, 
          function() {
            handleNoGeolocation(true);
          });
        } else {
          // Browser doesn't support Geolocation
          handleNoGeolocation(false);
        }

        directionsDisplay.setMap(map);

        google.maps.event.addListener(directionsDisplay, 'directions_changed', function() {
          computeTotalDistance(directionsDisplay.getDirections());
        });

        calcRoute();
      }

      function calcRoute() {

        var start = document.getElementById("pide_pickup").value;
        var end = document.getElementById("pide_dropoff").value;

        var request = {
          origin: start,
          destination: end,
          travelMode: google.maps.TravelMode.DRIVING
        };
        directionsService.route(request, function(response, status) {
          if (status == google.maps.DirectionsStatus.OK) {
            directionsDisplay.setDirections(response);
          }
        });
      }

      function computeTotalDistance(result) {
        var total = 0;
        var myroute = result.routes[0];
        for (var i = 0; i < myroute.legs.length; i++) {
          total += myroute.legs[i].distance.value;
        }
        total = total / 1000.0;
        document.getElementById('pide_distancia').innerHTML = total + ' km';
        

        if (total <= 7) {
          document.getElementById('pide_precio').innerHTML = '$' + '70' + ' billetes verdes (MXN)';
        };

        if (total >= 8 && total <= 12) {
          document.getElementById('pide_precio').innerHTML = '$' + '100' + ' billetes verdes (MXN)';
        };

        if (total >= 13 && total <= 17) {
          document.getElementById('pide_precio').innerHTML = '$' + '150' + ' billetes verdes (MXN)';
        };

        if (total >= 18 && total <= 22) {
          document.getElementById('pide_precio').innerHTML = '$' + '200' + ' billetes verdes (MXN)';
        };

        if (total >= 23) {
          document.getElementById('pide_precio').innerHTML = '$' + Math.ceil(total * 10) + ' billetes verdes (MXN)';
        };

      }

      function handleNoGeolocation(errorFlag) {
        if (errorFlag) {
          var content = 'Lo sentimos: El servicio de geolocalización falló.';
        } else {
          var content = 'Tu explorador de internet no permite geolocalizarte.';
        }

        var options = {
          map: map,
          position: new google.maps.LatLng(60, 105),
          content: content
        };

        var infowindow = new google.maps.InfoWindow(options);
        map.setCenter(options.position);
      }

      google.maps.event.addDomListener(window, 'load', initialize);

    </script>
  
    <section id="main" class="container 80%" style="margin-top: 3em !important">

      <div class="box">

        <div>

          <p>
            <label for="pide_pickup">¿A dónde pasamos por tu envío?</label>
            <input type="text" name="pide_pickup" id="pide_pickup" placeholder="Calle, número y colonia"/>
            <label for="pide_dropoff">¿A dónde lo llevamos?</label>
            <input type="text" name="pide_dropoff" id="pide_dropoff" placeholder="Calle, número y colonia"/>
            <input type="" value="Calcular distancia y precio" onclick="calcRoute()" class="btn backgroundColor" readonly/>
          </p>

          <h3>Precio y distancia estimados:</h3>
          <p>Distancia:
           
           <textarea id="pide_distancia"></textarea>
         </p>
         <br>
          <textarea id="pide_precio"></textarea>

        </div>

          <div class="row uniform 50%">

            <div id="map-container">
              <div id="map-canvas"></div>
            </div>

          </div>

      </div>

    </section>


   