config/routes.rb
Rails.application.routes.draw do

  get 'password_reseteos/new'

  get 'password_reseteos/edit'

  resources :password_reseteos, only: [:new, :create, :edit, :update]
  resources :envioempresas, only: [:create, :destroy]

  get 'ingresa' => 'empresessions#new'
  post 'ingresa' => 'empresessions#create'
  delete 'salir' => 'empresessions#destroy'

  get 'altaempresa' => 'empresas#nueva'

  resources :empresas

  get 'password_resets/new'

  get 'password_resets/edit'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'usuarios/new'

  root 'estaticas#home'

  get 'unete' => 'estaticas#unete'

  get 'acercade' => 'estaticas#acercade'

  get 'faq' => 'estaticas#faq'

  get 'politicas' => 'estaticas#politicas'

  get 'contacto' => 'estaticas#contacto'

  get 'privacidad' => 'estaticas#privacidad'

  get 'nuevacuenta' => 'usuarios#nueva'

  resources :usuarios
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  
  match '/cotizacion', to: 'pides#new', via: 'get'
  match '/cotizacion', to: 'pides#create', via: 'post'
  resources "cotizacion", only: [:new, :create]

end

app/controllers/empresessions_controller.rb
class EmpresessionsController < ApplicationController

  def new
  end

  def create
  	empresa = Empresa.find_by(email: params[:session][:email].downcase)
  	if empresa && empresa.authenticate(params[:session][:password])
  		ingresa empresa
  		params[:session][:remember_me] == '1' ? remember(empresa) : forget(empresa)
  		redirect_back_or empresa
  	else
  		flash.now[:danger] = 'Mail o contraseña inválido'
  		render 'new'
  	end
  end

  def destroy
  	cerrar_sesion if ingresado?
  	redirect_to root_url
  end

end

app/helpers/empresessions_helper.rb
module EmpresessionsHelper

	def ingresa(empresa)
		session[:empresa_id] = empresa.id
	end

	def remember(empresa)
		empresa.remember
		cookies.permanent.signed[:empresa_id] = empresa.id
		cookies.permanent[:remember_token] = empresa.remember_token
	end

	def current_empresa?(empresa)
    	empresa == current_empresa
  	end

	def current_empresa
	    if (empresa_id = session[:empresa_id])
	      @current_empresa ||= Empresa.find_by(id: empresa_id)
	    elsif (empresa_id = cookies.signed[:empresa_id])
	      empresa = Empresa.find_by(id: empresa_id)
	      if empresa && empresa.authenticated?(:remember, cookies[:remember_token])
	        ingresa empresa
	        @current_empresa = empresa
	      end
	    end
	end

	def ingresado?
		!current_empresa.nil?
	end

	def cerrar_sesion
		forget(current_empresa)
		session.delete(:empresa_id)
		@current_empresa = nil
	end

	def redirect_back_or(default)
		redirect_to(session[:forwarding_url] || default)
		session.delete(:forwarding_url)
	end

	def store_location
		session[:forwarding_url] = request.url if request.get?
	end

end

app/views/empresessions/new.html.erb
<div class="row">
	<div class="col-lg-6 col-lg-push-3 text-center">
		<h1>Ingresa a tu cuenta</h1>
	</div>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:session, url: ingresa_path) do |f| %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= link_to "(Olvidé mi password)", new_password_reseteo_path %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :remember_me, class: "checkbox inline" do %>
      <%= f.check_box :remember_me %>
      <span>Recordar mi sesión en ésta computadora</span>
      <% end %>

      <%= f.submit "Ingresa", class: "btn btn-primary" %>
    <% end %>

    <p>¿Deseas abrir una cuenta empresarial?</p>
    <p>Envianos un mail a <%= mail_to "socios@bicimensajero.com" %></p>
  </div>
</div>