config/routes.rb
Rails.application.routes.draw do

  get 'password_reseteos/new'

  get 'password_reseteos/edit'

  resources :password_reseteos, only: [:new, :create, :edit, :update]
  resources :envioempresas, only: [:create, :destroy]

  get 'ingresa' => 'empresessions#new'
  post 'ingresa' => 'empresessions#create'
  delete 'salir' => 'empresessions#destroy'

  get 'altaempresa' => 'empresas#nueva'

  resources :empresas

  get 'password_resets/new'

  get 'password_resets/edit'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'usuarios/new'

  root 'estaticas#home'

  get 'unete' => 'estaticas#unete'

  get 'acercade' => 'estaticas#acercade'

  get 'faq' => 'estaticas#faq'

  get 'politicas' => 'estaticas#politicas'

  get 'contacto' => 'estaticas#contacto'

  get 'privacidad' => 'estaticas#privacidad'

  get 'nuevacuenta' => 'usuarios#nueva'

  resources :usuarios
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  
  match '/cotizacion', to: 'pides#new', via: 'get'
  match '/cotizacion', to: 'pides#create', via: 'post'
  resources "cotizacion", only: [:new, :create]

end

app/views/layouts/_footer.html.erb
<footer id="footer-1 bg-dark">

          <div class="container">
                    <div class="row">
                        <div class="col-md-3 col-sm-6">
                          <%= image_tag 'logo-bicimensajero-light.png', alt: 'Logo', :class => 'logo' %>
                        </div>
                        
                    </div>
                    <!--end of row-->
                    <div class="row">
                        <div class="col-sm-6 margin-bottom-0">
                            <span class="sub">&copy; Copyright 2015 - Bicimensajero</span>
                            
                            <li style="list-style:none;"><i class="fa fa-bicycle iconsColor">&nbsp;<%= link_to "Contacto", contacto_path %></i></li>
                            <li style="list-style:none;">
                              <i class="fa fa-newspaper-o iconsColor">&nbsp;</i>
                              <span class="sub"><a href="http://blog.bicimensajero.com">Blog</a></span>
                            </li>
                            <li style="list-style:none;">
                              <i class="fa fa-hand-spock-o iconsColor">&nbsp;&nbsp;<%= link_to "Únete", unete_path %></i>
                            </li>
                            <li style="list-style:none;"><i class="fa fa-lock iconsColor">&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to "Privacidad", privacidad_path %></i></li>
                            <li style="list-style:none;">Ignacio Allende #21 Colonia Ampliación Torreblanca, 11289, México DF</li>
                            <li style="list-style:none;">
                              <i class="fa fa-envelope-o iconsColor">&nbsp;</i>
                              <span class="sub">amo@bicimensajero.com</span>
                            </li>
                            <li style="list-style:none;">
                              <i class="fa fa-phone iconsColor">&nbsp;</i>
                              <span class="sub">+52 55 3555 1151</span>
                            </li>
                        </div>
                        <div class="col-sm-6 text-right">
                            <h4>Visítanos en redes sociales</h4>
                            <ul class="list-inline social-list">
                                <li>
                                    <a href="https://twitter.com/BicimensajeroMX" target="_blank">
                                        <i class="fa fa-twitter fa-3x"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="https://www.facebook.com/MensajerosMX" target="_blank">
                                        <i class="fa fa-facebook fa-3x"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="https://instagram.com/explore/tags/messlife/" target="_blank">
                                        <i class="fa fa-instagram fa-3x"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="https://www.youtube.com/user/MensajerosDF" target="_blank">
                                        <i class="fa fa-youtube fa-3x"></i>
                                    </a>
                                </li>                                
                            </ul>
                        </div>
                    </div>
                </div>


<!--Start of Tawk.to Script-->
<script type="text/javascript">
var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
(function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
s1.async=true;
s1.src='https://embed.tawk.to/55bf83623bebe0ba0d3d947e/default';
s1.charset='UTF-8';
s1.setAttribute('crossorigin','*');
s0.parentNode.insertBefore(s1,s0);
})();
</script>
<!--End of Tawk.to Script-->


<script type="text/javascript">
$(document).ready(function(){
  setTimeout(function(){
    $('.alert-warning').slideUp();
  }, 7000);
 })
</script>

<script type="text/javascript">
$(document).ready(function(){
  setTimeout(function(){
    $('.alert-success').slideUp();
  }, 7000);
 })
</script>

</footer>

app/views/layouts/_header.html.erb
		<div class="nav-container">
            <a id="top"></a>
            <nav>

                <div class="nav-bar">
                    <div class="module left">
                        <%= link_to root_path do %>
                        	<%= image_tag 'logo-bicimensajero-light.png', width: 200, alt: 'Bicimensajero' %>
                        <% end %>
                    </div>
                    <div class="module widget-handle mobile-toggle right visible-sm visible-xs">
                        <i class="ti-menu"></i>
                    </div>
                    <div class="module-group right">
                        <div class="module left">
                            <ul class="menu">

                                <% if logged_in? && current_usuario.admin? %>

                                <%= link_to "Lista de usuarios", usuarios_path, :class => 'btn btn-sm btn-rounded' %>
                                <%= link_to "Lista de empresas", empresas_path, :class => 'btn btn-sm btn-rounded' %>
                                <%= link_to "Da de alta una empresa", altaempresa_path, :class => 'btn btn-sm btn-rounded' %>
                                <%= link_to "Cotiza y pide", root_path, :class => 'btn btn-sm btn-rounded' %>

                                <% elsif logged_in? %>

                                <li>
                                    <%= link_to "Mis pedidos", current_usuario %>
                                </li>
                                <li><%= link_to "Pide un bicimensajero", root_path, :class => 'btn btn-sm noinputborder' %>
                                </li>
                                <li>
                                    <a href="http://blog.bicimensajero.com" target="_blank">
                                        Blog
                                    </a>
                                    
                                </li>

                                <% elsif ingresado? %>
                                <li><%= link_to "Mis pedidos", current_empresa %></li>
                                <li><%= link_to "Pide un bicimensajero", root_path, :class => 'btn btn-sm noinputborder' %>
                                </li>
                                <li><a href="http://blog.bicimensajero.com" target="_blank">Blog</a></li>

                                <% else %>

                                <li>
                                    <%= link_to "Inicio", root_path %>
                                </li>
                                <li>
                                    <%= link_to "Únete", unete_path %>
                                </li>
                                <li>
                                    <a href="http://blog.bicimensajero.com" target="_blank">
                                        Blog
                                    </a>
                                    
                                </li>

                                <li><%= link_to "Empresas", ingresa_path %></li>

                                <% end %>
                               
                            </ul>
                        </div>
                        <!--end of menu module-->
                        <div class="module widget-handle cart-widget-handle left">
                            <div class="cart">
                                <i class="ti-user"></i>
                            </div>
                            <div class="function">
                                <div class="widget">                                 
                                    <hr>

                                    <% if logged_in? && current_usuario.admin? %>
                                    
                                    <%= link_to "Perfil", current_usuario, :class => 'btn btn-sm btn-filled' %>
                                    <%= link_to "Ajustes de mi cuenta", edit_usuario_path(current_usuario), :class => 'btn btn-sm btn-filled' %>
									<%= link_to "Cerrar sesión", logout_path, method: "delete", :class => 'btn btn-sm btn-filled' %>

									<% elsif logged_in? %>

									<%= link_to "Perfil", current_usuario, :class => 'btn btn-sm btn-filled' %>
                                    <%= link_to "Ajustes de mi cuenta", edit_usuario_path(current_usuario), :class => 'btn btn-sm btn-filled' %>
									<%= link_to "Cerrar sesión", logout_path, method: "delete", :class => 'btn btn-sm btn-filled' %>

                                    <% elsif ingresado? %>

                                    <%= link_to "Perfil", current_empresa, :class => 'btn btn-sm btn-filled' %>
                                    <%= link_to "Ajustes de mi cuenta", edit_empresa_path(current_empresa), :class => 'btn btn-sm btn-filled' %>
                                    <%= link_to "Cerrar sesión", salir_path, method: "delete", :class => 'btn btn-sm btn-filled' %>

									<% else %>

									<%= link_to "Crea una cuenta", nuevacuenta_path, :class => 'btn btn-sm' %>
									<%= link_to "Ingresa a tu cuenta", login_path, :class => 'btn btn-sm btn-filled' %>	

									<% end %>

                                </div>
                                <!--end of widget-->
                            </div>
                        </div>
                        <!-- Idioma -->
                        <!--
                        <div class="module widget-handle language left">
                            <ul class="menu">
                                <li class="has-dropdown">
                                    <a href="elements-tabs.html#">ENG</a>
                                    <ul>
                                        <li>
                                            <a href="elements-tabs.html#">French</a>
                                        </li>
                                        <li>
                                            <a href="elements-tabs.html#">Deutsch</a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        -->
                    </div>
                    <!--end of module group-->
                </div>
            </nav>
        </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <% if content_for? :for_head %>
    <%= yield :for_head %>
  <% end %>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=0.8">
  <title><%= yield(:title) %>Bicimensajero </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400%7CRaleway:100,400,300,500,600,700%7COpen+Sans:400,500,600' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  <meta name="keywords" content="Mensajería,sostenible,logística,Bicimensajero,Bicimensajeros,sustentable,urbana,urbano,bicicleta,on-demand,economía,colaborativa">

  <meta property="og:site_name" content="Bicimensajero"/>
  <meta property="og:url" content="http://www.bicimensajero.com" />
  <meta property="og:description" content="Servicio de logística urbana on-demand: Implementando principios de economía colaborativa. Checa cuanto CO2 le estás ahorrando al planeta." />
  <meta property="og:image" content="http://bicimensajero.com/assets/banner1-5562325e01be936c1596391c37fd168de85360d62b261ba68a2d72eabb158ea8.jpg"/>  
  
  <!-- Start of Google Analytics -->
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-65260813-1', 'auto');
  ga('send', 'pageview');

  </script>  
  <!--End of Google Analytics-->

</head>
<body data-no-turbolink="true">

        <div class="nav-container">
          <%= render 'layouts/header' %>
        </div>
      


    <!--Mostrar Terminal-->
    <div class="">

      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>

      <%= render 'layouts/footer' %>

      <%= debug(params) if Rails.env.development? %>

    </div>

</body>
</html>